//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDocForum.FTSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTSearchService.FTSearchService")]
    public interface FTSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTSearchService/StartInstance", ReplyAction="http://tempuri.org/FTSearchService/StartInstanceResponse")]
        void StartInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTSearchService/ClearInstance", ReplyAction="http://tempuri.org/FTSearchService/ClearInstanceResponse")]
        void ClearInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTSearchService/IndexText", ReplyAction="http://tempuri.org/FTSearchService/IndexTextResponse")]
        void IndexText(string aliasName, string contentText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTSearchService/SearchPhrase", ReplyAction="http://tempuri.org/FTSearchService/SearchPhraseResponse")]
        string[] SearchPhrase(string phrase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FTSearchServiceChannel : BigDocForum.FTSearchService.FTSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FTSearchServiceClient : System.ServiceModel.ClientBase<BigDocForum.FTSearchService.FTSearchService>, BigDocForum.FTSearchService.FTSearchService {
        
        public FTSearchServiceClient() {
        }
        
        public FTSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FTSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartInstance() {
            base.Channel.StartInstance();
        }
        
        public void ClearInstance() {
            base.Channel.ClearInstance();
        }
        
        public void IndexText(string aliasName, string contentText) {
            base.Channel.IndexText(aliasName, contentText);
        }
        
        public string[] SearchPhrase(string phrase) {
            return base.Channel.SearchPhrase(phrase);
        }
    }
}
